#!/usr/bin/env bash
# Script to tell the story of users in /etc/passwd

# Read the /etc/passwd file line by line
while IFS=: read -r username _ user_id _ home_directory shell info; do
    # Output the user story
    echo "The user $username is part of the $user_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode x, more info about the user here: $info"
done < /etc/passwd

