#!/usr/bin/env bash
# This script tells a story based on the /etc/passwd file

# Set IFS to colon (:) to split each line correctly
IFS=':'

# Read the /etc/passwd file line by line
while read -r username password user_id group_id user_info home_directory shell; do
    # Display the formatted output
    echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd

