#!/usr/bin/env bash
# This script displays "Best School" 10 times

for i in {1..10}
do
  echo "Best School"
done
#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop

i=1
while [ $i -le 10 ]
do
  echo "Best School"
  ((i++))
done
#!/usr/bin/env bash
# This script displays "Best School" 10 times using an until loop

i=1
until [ $i -gt 10 ]
do
  echo "Best School"
  ((i++))
done

