#!/bin/bash

while true; do
    echo "To infinity and beyond"
    sleep 1
done
	                                                                                                                                                                                                                                                                                                 i        
        

